[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 600
startCommand = "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"
